version: '3.8'

services:
  fronted:
    build:
      context: ./Frontend
      dockerfile: dockerfile
    container_name: frontend
    ports:
      - "4200:80"
  
  repository-manager:
    build:
      context: ./Repository-Manager
      dockerfile: dockerfile
    container_name: repository-manager
    ports:
      - "5000:5000"

  uvengine-resolver:
    build:
      context: ./UVEngine-Resolver
      dockerfile: dockerfile
    container_name: uvengine-resolver
    ports:
      - "5001:5001"
    depends_on:
      - repository-manager
  
  nginx-reverse-proxy:
    build:
      context: ./Nginx-Reverse-Proxy
      dockerfile: dockerfile
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"

